/*
SETUP DATABASE ENVIROMENT FOR HELPDESK
Michi von Ah - April/May 2023
FOR POSTGRESQL
*/

-- CREATE DATABASE
/*USE MASTER;

DROP DATABASE IF EXISTS helpdesk;

CREATE DATABASE helpdesk;

USE helpdesk;*/

-- CREATE TABLES
CREATE TABLE "user"(
	userid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(30),
	displayname VARCHAR(50),
	mail VARCHAR(250),
	password VARCHAR(99),
	active BOOLEAN,
	fk_usergroupid INTEGER,
	PRIMARY KEY(userid)
);

CREATE TABLE "usergroup"(
	usergroupid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	admin BOOLEAN,
	PRIMARY KEY(usergroupid)
);

CREATE TABLE "ticket"(
	ticketid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(120),
    description VARCHAR(240),
	fk_statusid INTEGER,
    fk_userid INTEGER,
    fk_customerid INTEGER,
	fk_organizationid INTEGER,
	PRIMARY KEY(ticketid)
);

CREATE TABLE "status"(
	statusid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	PRIMARY KEY(statusid)
);

CREATE TABLE "customer"(
	customerid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
    mail VARCHAR(250),
    phone VARCHAR(14),
    birthdate DATE,
    website VARCHAR(250),
    address VARCHAR(250),
    notes VARCHAR(250),
	fk_organizationid INTEGER,
	PRIMARY KEY(customerid)
);

CREATE TABLE "organization"(
	organizationid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
    mail VARCHAR(250),
    domain VARCHAR(250),
	allow_selfregister BOOLEAN,
	fk_userid INTEGER,
	PRIMARY KEY(organizationid)
);

CREATE TABLE "userorganization"(
	userorganizationid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	fk_userid INTEGER,
	fk_organizationid INTEGER,
	PRIMARY KEY(userorganizationid)
);

-- SET FOREIGN KEYS
ALTER TABLE "user" ADD FOREIGN KEY(fk_usergroupid) REFERENCES usergroup(usergroupid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_statusid) REFERENCES status(statusid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_userid) REFERENCES "user"(userid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_customerid) REFERENCES customer(customerid);

-- SET DEFAULT VALUES
ALTER TABLE "user" ALTER COLUMN "active" SET DEFAULT True;
ALTER TABLE "user" ALTER COLUMN "fk_usergroupid" SET DEFAULT 2;
ALTER TABLE "usergroup" ALTER COLUMN "admin" SET DEFAULT False;
ALTER TABLE "organization" ALTER COLUMN "allow_selfregister" SET DEFAULT False;
ALTER TABLE "ticket" ALTER COLUMN "fk_statusid" SET DEFAULT 1;


-- CREATE DEFAULT USER GROUPS
INSERT INTO usergroup (name, admin) VALUES
('SYSTEM', true),
('user', false),
('admins', true);

-- CREATE DEFAULT USERS
INSERT INTO "user" (username, displayname, password, fk_usergroupid) VALUES
    ('SYSTEM', 'SYSTEM', '0f8afe0239e42215735340b80c8de401aa7304b2470304165b4c15e37ee392e5', 1),
    ('admin', 'Administrator', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 3);

-- CREATE STATUS TYPES
INSERT INTO "status" (name) VALUES
    ('Open'),
    ('Closed');
