/*
SETUP DATABASE ENVIROMENT FOR HELPDESK
Michi von Ah - April 2023
FOR POSTGRESQL
*/

-- CREATE DATABASE
/*USE MASTER;

DROP DATABASE IF EXISTS helpdesk;

CREATE DATABASE helpdesk;

USE helpdesk;*/

-- CREATE TABLES
CREATE TABLE "user"(
	userid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(30),
	mail VARCHAR(250),
	password VARCHAR(99),
	fk_usergroupid INTEGER,
	PRIMARY KEY(userid)
);

CREATE TABLE "usergroup"(
	usergroupid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	admin BOOLEAN,
	PRIMARY KEY(usergroupid)
);

CREATE TABLE "ticket"(
	ticketid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(120),
    description VARCHAR(240),
	fk_statusid INTEGER,
    fk_userid INTEGER,
    fk_customerid INTEGER,
	PRIMARY KEY(ticketid)
);

CREATE TABLE "status"(
	statusid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	PRIMARY KEY(statusid)
);

CREATE TABLE "customer"(
	customerid INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
    mail VARCHAR(250),
    phone VARCHAR(14),
    birthdate DATE,
    website VARCHAR(250),
    address VARCHAR(250),
    notes VARCHAR(250),
	PRIMARY KEY(customerid)
);

-- SET FOREIGN KEYS
ALTER TABLE "user" ADD FOREIGN KEY(fk_usergroupid) REFERENCES usergroup(usergroupid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_statusid) REFERENCES status(statusid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_userid) REFERENCES "user"(userid);
ALTER TABLE ticket ADD FOREIGN KEY(fk_customerid) REFERENCES customer(customerid);

-- CREATE DEFAULT USER GROUPS
INSERT INTO usergroup (name, admin) VALUES
('SYSTEM', true),
('user', false);

-- CREATE DEFAULT USERS
INSERT INTO "user" (username, password) VALUES
    ('SYSTEM', '0f8afe0239e42215735340b80c8de401aa7304b2470304165b4c15e37ee392e5'),
    ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');

-- CREATE STATUS TYPES
INSERT INTO "status" (name) VALUES
    ('Open'),
    ('Closed');

-- CREATE DEFAULT TICKET
INSERT INTO "ticket" (name, fk_statusid, fk_userid, fk_customerid) VALUES
    ('Hello World!', 2, 1, 1);
